movieapp/urls.py
from django.urls import path,include
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))

]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    decs=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='images')




    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','decs','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from . models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        "movielist":movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)

    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        decs=request.POST.get('decs',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,decs=decs,year=year,img=img)
        movie.save()
        return redirect('/')
    return  render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name" placeholder="Enter Movie Name"><br>
        <input type="text" name="decs" placeholder="Enter Movie decsriptions"><br>
        <input type="text" name="year" placeholder="Enter your Movie year"><br>
        <input type="file" name="img"><br>
        <input class="btn btn-success" type="submit">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie World</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movie World
  </a>
    <a  class="btn btn-secondary" href="{% url 'movieapp:add_movie' %}" >Add New Movie</a><br>
</nav>



{% block body %}
{% endblock %}

</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

<div class="alert alert-danger" role="alert">
  Are You Sure Want To Delete ?
    <button type="submit" class="btn btn-danger">Yes</button>
</div>

</form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

                        <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{movie.img.url}}" alt="Card image cap">
                        <div class="card-body">
                        <h5 class="card-title">{{movie.name}}</h5>

                        </div>


                        </div>



</div>
                        <div class="card" style="width: 18rem;">
                        <div class="card-body">
                        <h5 class="card-title">{{movie.name}}</h5>
                         <p class="card-text">{{movie.decs}}</p>
                            <p class="card-text">Year:{{movie.year}}</p>

                         <a href="{% url 'movieapp:update' movie.id %}" class="btn btn-warning">Update</a>
                            <a href="{% url 'movieapp:delete' movie.id %}" class="btn btn-danger">Delete</a>

                        </div>




        </div>
    </div>
</div>




{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method= "POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form.as_p}}
    <input  class="btn btn-success" type="submit">

</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">

    <div class="row">
        {% for i in movielist %}

        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="250" height="350">
            <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>
            <p class="card-text">{{i.desc}}</p>
            <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Details</a>

            </div>


            </div><br>
        </div>
        {% endfor %}

    </div>

</div>





{% endblock %}